# -*- coding: utf-8 -*-
"""Market Basket Analysis Using Apriori Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyfo0KAuilAkVgkDg3H79c9bxOUpD8I4

## Apriori Algorithm Implementation in R using 'arules' library

Association mining is usually done on transactions data from a retail market or from an online e-commerce store. Since most transactions data is large, the apriori algorithm makes it easier to find these patterns or rules quickly. Association Rules are widely used to analyze retail basket or transaction data, and are intended to identify strong rules discovered in transaction data using measures of interestingness, based on the concept of strong rules.

Apriori uses a "bottom up" approach, where frequent subsets are extended one item at a time (a step known as candidate generation), and groups of candidates are tested against the data. The algorithm terminates when no further successful extensions are found.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/549fa6a5f46897d137b5d704ef7f30b6ba36d4de)

## Import Required libraries
"""

if(sessionInfo()['basePkgs']=="dplyr" | sessionInfo()['otherPkgs']=="dplyr"){
  detach(package:dplyr, unload=TRUE)
}

if(sessionInfo()['basePkgs']=="tm" | sessionInfo()['otherPkgs']=="tm"){
  detach(package:sentiment, unload=TRUE)
  detach(package:tm, unload=TRUE)
}

library(plyr)
library(arules)
library(arulesViz)

options("repos")[[1]][1]

options(repos="https://cran.rstudio.com")

install.packages("plyr")
install.packages("arules")
install.packages("arulesViz")
library("plyr")
library("arules")
library("arulesViz")

"""## Import the dataset"""

groceries <- read.csv("https://firebasestorage.googleapis.com/v0/b/budi-23.appspot.com/o/dataset%2FMarket%20Basket%20Analysis%20using%20apriori%20Algorithm%2FGroceries_dataset.csv?alt=media&token=8059b5e8-3a3c-4b5f-a914-2960210324c8")
class(groceries)

"""## Data Cleaning and Exploration"""

str(groceries)

head(groceries)

"""### Checking NA values"""

sum(is.na(groceries))

"""### Convert member number to numeric"""

sorted <- groceries[order(groceries$Member_number),]

"""### Convert item description to categorical format"""

sorted$Member_number <- as.numeric(sorted$Member_number)
str(sorted)

"""### Group all the items that were bought together by the same customer on the same date"""

itemList <- ddply(sorted, c("Member_number","Date"), function(df1)paste(df1$itemDescription,collapse = ","))
                  
head(itemList,15)

"""### Remove member number and date"""

itemList$Member_number <- NULL
itemList$Date <- NULL
colnames(itemList) <- c("itemList")

write.csv(itemList,"ItemList.csv", quote = FALSE, row.names = TRUE)
head(itemList)

"""## Convert CSV file to Basket Format"""

txn = read.transactions(file="ItemList.csv", rm.duplicates= TRUE, format="basket",sep=",",cols=1);
print(txn)

"""There are in total 14,964 transactions with 168 distinct products.

### Remove quotes from Transaction
"""

txn@itemInfo$labels <- gsub("\"","",txn@itemInfo$labels)

"""## Apriori Algorithm

The apriori() generates the most relevent set of rules from a given transaction data. It also shows the support, confidence and lift of those rules. These three measure can be used to decide the relative strength of the rules. So what do these terms mean?

Lets consider the rule X => Y in order to compute these metrics.

![](https://s3.ap-south-1.amazonaws.com/techleer/243.jpg)
"""

basket_rules <- apriori(txn, parameter = list(minlen=2, sup = 0.001, conf = 0.05, target="rules"))

"""### Total rules generated"""

print(length(basket_rules))

summary(basket_rules)

"""### Inspecting the basket rules"""

inspect(basket_rules[1:20])

"""## Visualizing the Association Rules"""

plot(basket_rules, jitter = 0)

plot(basket_rules, method = "grouped", control = list(k = 5))

"""### Graph of first 20 rules"""

plot(basket_rules[1:20], method="graph")

"""### Graph of first 50 rules"""

plot(basket_rules[1:50], method="graph")

"""### Parallel coordinates plot"""

plot(basket_rules[1:20], method="paracoord")

"""## Most Frequent Products"""

itemFrequencyPlot(txn, topN = 10)

"""## Changing hyperparameters"""

basket_rules2 <- apriori(txn, parameter = list(minlen=3, sup = 0.001, conf = 0.1, target="rules"))

print(length(basket_rules2))

summary(basket_rules2)

inspect(basket_rules2)

plot(basket_rules2, method="graph")

plot(basket_rules2, method="paracoord")